name: aptos
description: Aptos Dart SDK — a pure-Dart client library for the Aptos blockchain.
version: 1.0.0
repository: https://github.com/0xmove/aptos

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.4.0
  ed25519_edwards: ^0.3.1
  pointycastle: ^3.9.1
  bip39: ^1.0.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
