/// Input data types for the transaction building pipeline.
///
/// Union types are modeled either as `typedef X = Object` (runtime-checked)
/// or as abstract base classes with concrete subclasses.
library;

import '../api/aptos_config.dart';
import '../core/account_address.dart';
import '../core/crypto/public_key.dart';
import '../types/move_types.dart';
import '../types/transaction_responses.dart';
import '../types/types.dart';
import 'authenticator/account.dart';
import 'instances/raw_transaction.dart';
import 'instances/transaction_argument.dart';
import 'instances/transaction_payload.dart';
import 'type_tag/type_tag.dart';

export 'instances/raw_transaction.dart' show AnyRawTransaction;

/// Inputs for type arguments of entry functions, view functions and scripts.
///
/// This is either a [TypeTag] or a [String] representation of a type tag such
/// as `u8`, `bool`, `address`, `vector<u64>`, or
/// `0x1::aptos_coin::AptosCoin`.
typedef TypeArgument = Object;

/// Entry function arguments for building a raw transaction using remote ABI:
/// raw values such as `bool`, `int`, `BigInt`, `String`, `null` (to support
/// empty options), `Uint8List`, `ByteBuffer`, or a `List` of those (possibly
/// mixed with already-encoded [EntryFunctionArgumentTypes] values).
typedef SimpleEntryFunctionArgumentTypes = Object;

/// Entry function arguments for building a raw transaction using
/// BCS-serialized arguments (`Bool`, `U8`..`U256`, `I8`..`I256`,
/// `AccountAddress`, `MoveVector`, `MoveOption`, `MoveString`,
/// `MoveStructArgument`, `MoveEnumArgument`, `FixedBytes`).
///
/// All of them implement the [EntryFunctionArgument] interface.
typedef EntryFunctionArgumentTypes = EntryFunctionArgument;

/// Script function arguments for building raw transactions using
/// BCS-serialized arguments.
typedef ScriptFunctionArgumentTypes = ScriptFunctionArgument;

/// The transaction payload type generated by the
/// `generateTransactionPayload()` function: a `TransactionPayloadEntryFunction`,
/// `TransactionPayloadScript`, `TransactionPayloadMultiSig`,
/// `TransactionInnerPayload` or `TransactionPayloadEncryptedPayload`.
///
/// All of these extend [TransactionPayload] in the Dart SDK.
typedef AnyTransactionPayloadInstance = TransactionPayload;

// TRANSACTION GENERATION TYPES //

/// Optional options to set when generating a transaction.
///
/// Combines sequence-number based options (`accountSequenceNumber`) and
/// orderless options (`replayProtectionNonce`); the two fields are mutually
/// exclusive at runtime (enforced by `generateRawTransaction`).
///
/// When `encrypted` is set, the payload is encrypted against the node's
/// per-epoch batch-encryption key before submission; the remaining
/// encryption fields supply (or override) the signer authentication keys that
/// go into the ciphertext's associated data, and an optional claimed entry
/// function that fee payers / multisig co-signers can inspect without
/// decrypting.
class InputGenerateTransactionOptions {
  /// Maximum total gas to spend for this transaction.
  final int? maxGasAmount;

  /// Price to be paid per gas unit.
  final int? gasUnitPrice;

  /// The blockchain timestamp (Unix seconds) at which the blockchain would
  /// discard this transaction.
  final int? expireTimestamp;

  /// The sequence number for the transaction. If not provided it is fetched
  /// from the network.
  final BigInt? accountSequenceNumber;

  /// The replay protection nonce for an orderless transaction. When set, the
  /// transaction sequence number is `u64::MAX` and the payload is wrapped in
  /// a `TransactionInnerPayloadV1`.
  final BigInt? replayProtectionNonce;

  /// When true, encrypt the payload against the node's batch-encryption key.
  final bool? encrypted;

  /// The sender's authentication key for the encrypted-payload associated
  /// data. An `AuthenticationKey` or a `HexInput`; fetched from chain when
  /// omitted. Only used when [encrypted] is true.
  final Object? senderAuthenticationKey;

  /// The secondary signers' authentication keys, one per secondary signer
  /// address, in order. Each entry is an `AuthenticationKey` or `HexInput`;
  /// leave an entry null to fetch it from chain. Only used when [encrypted].
  final List<Object?>? secondarySignerAuthenticationKeys;

  /// The fee payer's authentication key. An `AuthenticationKey` or `HexInput`;
  /// fetched from chain when omitted. Only used when [encrypted].
  final Object? feePayerAuthenticationKey;

  /// An optional claim about the entry function inside the encrypted payload,
  /// letting fee payers / multisig co-signers see the module (and optionally
  /// the function name) without decrypting. A [ClaimedEntryFunction] or an
  /// [InputClaimedEntryFunction]. Only used when [encrypted].
  final Object? claimedEntryFunction;

  const InputGenerateTransactionOptions({
    this.maxGasAmount,
    this.gasUnitPrice,
    this.expireTimestamp,
    this.accountSequenceNumber,
    this.replayProtectionNonce,
    this.encrypted,
    this.senderAuthenticationKey,
    this.secondarySignerAuthenticationKeys,
    this.feePayerAuthenticationKey,
    this.claimedEntryFunction,
  });
}

/// A lightweight description of the entry function claimed by an encrypted
/// payload: the fully-qualified `module` (e.g. `0x1::coin`) and optionally the
/// `functionName`. Resolved into a [ClaimedEntryFunction] by the builder.
class InputClaimedEntryFunction {
  final String module;
  final String? functionName;
  const InputClaimedEntryFunction({required this.module, this.functionName});
}

/// The data needed to generate a transaction payload: an
/// [InputEntryFunctionData], [InputScriptData], [InputMultiSigData], or
/// [InputMultiSigScriptData].
abstract class InputGenerateTransactionPayloadData {
  const InputGenerateTransactionPayloadData();
}

/// The data needed to generate an Entry Function payload.
class InputEntryFunctionData extends InputGenerateTransactionPayloadData {
  /// The function to be called, in the format
  /// `moduleAddress::moduleName::functionName`.
  final MoveFunctionId function;

  /// Type arguments for the function, as [TypeTag]s or their string
  /// representations.
  final List<TypeArgument>? typeArguments;

  /// The arguments to pass to the function: raw values
  /// ([SimpleEntryFunctionArgumentTypes]), already-encoded BCS values
  /// ([EntryFunctionArgumentTypes]), or `null` for empty options.
  final List<Object?>? functionArguments;

  /// An optional ABI override. When provided, the remote ABI fetch is
  /// skipped.
  final EntryFunctionABI? abi;

  const InputEntryFunctionData({
    required this.function,
    this.typeArguments,
    this.functionArguments,
    this.abi,
  });
}

/// The data needed to generate a Multi Sig payload wrapping an entry
/// function, including the multisig address.
class InputMultiSigData extends InputEntryFunctionData {
  /// The multisig account address the transaction will be executed as.
  final AccountAddressInput multisigAddress;

  const InputMultiSigData({
    required this.multisigAddress,
    required super.function,
    super.typeArguments,
    super.functionArguments,
    super.abi,
  });
}

/// The data needed to generate a Script payload.
class InputScriptData extends InputGenerateTransactionPayloadData {
  /// The Move script bytecode, as a hex string or `Uint8List`.
  final HexInput bytecode;

  /// Type arguments for the script.
  final List<TypeArgument>? typeArguments;

  /// The BCS-serializable arguments the script function requires.
  final List<ScriptFunctionArgument> functionArguments;

  const InputScriptData({
    required this.bytecode,
    this.typeArguments,
    required this.functionArguments,
  });
}

/// The data needed to generate a Multi Sig payload wrapping a Script.
class InputMultiSigScriptData extends InputScriptData {
  /// The multisig account address the transaction will be executed as.
  final AccountAddressInput multisigAddress;

  const InputMultiSigScriptData({
    required this.multisigAddress,
    required super.bytecode,
    super.typeArguments,
    required super.functionArguments,
  });
}

/// The data needed to generate a View Function payload.
class InputViewFunctionData {
  /// The function to be called, in the format
  /// `moduleAddress::moduleName::functionName`.
  final MoveFunctionId function;

  final List<TypeArgument>? typeArguments;

  final List<Object?>? functionArguments;

  /// An optional ABI override. When provided, the remote ABI fetch is
  /// skipped.
  final ViewFunctionABI? abi;

  const InputViewFunctionData({
    required this.function,
    this.typeArguments,
    this.functionArguments,
    this.abi,
  });
}

/// Data needed for a generic function ABI, applicable to both view and entry
/// functions.
class FunctionABI {
  /// The generic type parameters of the function.
  final List<MoveFunctionGenericTypeParam> typeParameters;

  /// The parameter types of the function (excluding leading signers for
  /// entry functions).
  final List<TypeTag> parameters;

  const FunctionABI({required this.typeParameters, required this.parameters});
}

/// An Entry function's ABI, enabling type checking and input conversion for
/// ABI-based transaction submissions.
class EntryFunctionABI extends FunctionABI {
  /// The number of leading `signer`/`&signer` parameters that were removed
  /// from [FunctionABI.parameters].
  final int? signers;

  const EntryFunctionABI({
    this.signers,
    required super.typeParameters,
    required super.parameters,
  });
}

/// A view function's ABI, providing type checking and input conversion for
/// ABI-based view requests.
class ViewFunctionABI extends FunctionABI {
  /// The return types of the view function.
  final List<TypeTag> returnTypes;

  const ViewFunctionABI({
    required super.typeParameters,
    required super.parameters,
    required this.returnTypes,
  });
}

// USER INPUT TYPES //

/// Unified type holding the user data input for generating a transaction:
/// either an [InputGenerateSingleSignerRawTransactionData] or an
/// [InputGenerateMultiAgentRawTransactionData].
abstract class InputGenerateTransactionData {
  /// The address of the account sending the transaction.
  AccountAddressInput get sender;

  /// The payload data for the transaction.
  InputGenerateTransactionPayloadData get data;

  /// Optional transaction options.
  InputGenerateTransactionOptions? get options;

  /// Indicates if a fee payer is included (sponsored transaction).
  bool get withFeePayer;

  /// Addresses of any secondary signers, or `null` for a single signer
  /// transaction. Used to discriminate the transaction data union.
  List<AccountAddressInput>? get secondarySignerAddresses;
}

/// Holds user input data for generating a single signer transaction.
class InputGenerateSingleSignerRawTransactionData
    implements InputGenerateTransactionData {
  @override
  final AccountAddressInput sender;

  @override
  final InputGenerateTransactionPayloadData data;

  @override
  final InputGenerateTransactionOptions? options;

  @override
  final bool withFeePayer;

  /// Always `null` for a single signer transaction.
  @override
  List<AccountAddressInput>? get secondarySignerAddresses => null;

  const InputGenerateSingleSignerRawTransactionData({
    required this.sender,
    required this.data,
    this.options,
    this.withFeePayer = false,
  });
}

/// Holds user data input for generating a multi-agent transaction.
class InputGenerateMultiAgentRawTransactionData
    implements InputGenerateTransactionData {
  @override
  final AccountAddressInput sender;

  @override
  final InputGenerateTransactionPayloadData data;

  @override
  final List<AccountAddressInput> secondarySignerAddresses;

  @override
  final InputGenerateTransactionOptions? options;

  @override
  final bool withFeePayer;

  const InputGenerateMultiAgentRawTransactionData({
    required this.sender,
    required this.data,
    required this.secondarySignerAddresses,
    this.options,
    this.withFeePayer = false,
  });
}

// TRANSACTION SIMULATION TYPES //

/// The data required to simulate a transaction, typically generated by
/// `buildTransaction()`.
class InputSimulateTransactionData {
  /// The transaction to simulate, probably generated by `buildTransaction()`.
  final AnyRawTransaction transaction;

  /// For a single signer transaction. Optional: `null` skips the public/auth
  /// key check during the transaction simulation.
  final PublicKey? signerPublicKey;

  /// For a fee payer or multi-agent transaction that requires additional
  /// signers. Individual entries may be `null` to skip the corresponding
  /// auth key check.
  final List<PublicKey?>? secondarySignersPublicKeys;

  /// For a fee payer transaction (aka Sponsored Transaction).
  final PublicKey? feePayerPublicKey;

  final InputSimulateTransactionOptions? options;

  const InputSimulateTransactionData({
    required this.transaction,
    this.signerPublicKey,
    this.secondarySignersPublicKeys,
    this.feePayerPublicKey,
    this.options,
  });
}

/// Options for simulating a transaction.
class InputSimulateTransactionOptions {
  final bool? estimateGasUnitPrice;
  final bool? estimateMaxGasAmount;
  final bool? estimatePrioritizedGasUnitPrice;

  const InputSimulateTransactionOptions({
    this.estimateGasUnitPrice,
    this.estimateMaxGasAmount,
    this.estimatePrioritizedGasUnitPrice,
  });
}

// TRANSACTION SUBMISSION TYPES //

/// Holds user data input for submitting a transaction.
class InputSubmitTransactionData {
  /// The raw transaction data.
  final AnyRawTransaction transaction;

  /// The authenticator for the sender's account.
  final AccountAuthenticator senderAuthenticator;

  /// Optional authenticator for the fee payer's account.
  final AccountAuthenticator? feePayerAuthenticator;

  /// Optional array of authenticators for additional signers.
  final List<AccountAuthenticator>? additionalSignersAuthenticators;

  /// Additional parameters that will be passed to the transaction submitter
  /// plugin, if configured.
  final Map<String, Object?>? pluginParams;

  /// Overrides the configured transaction submitter (if any).
  ///
  /// NOTE: passing `null` explicitly to ignore a configured transaction
  /// submitter is handled by the api layer.
  final TransactionSubmitter? transactionSubmitter;

  const InputSubmitTransactionData({
    required this.transaction,
    required this.senderAuthenticator,
    this.feePayerAuthenticator,
    this.additionalSignersAuthenticators,
    this.pluginParams,
    this.transactionSubmitter,
  });
}

/// Implement this interface to override the default transaction submission
/// behavior, for example to submit transactions via a gas station.
abstract class TransactionSubmitter {
  /// Submit a transaction to the Aptos blockchain, or to something that will
  /// do it on your behalf (e.g. a gas station).
  Future<PendingTransactionResponse> submitTransaction({
    required AptosConfig aptosConfig,
    required AnyRawTransaction transaction,
    required AccountAuthenticator senderAuthenticator,
    AccountAuthenticator? feePayerAuthenticator,
    List<AccountAuthenticator>? additionalSignersAuthenticators,
    Map<String, Object?>? pluginParams,
  });
}

/// Determines if the provided payload data is script data input.
///
/// A simple type check, since the payload data union is modeled with classes.
bool isScriptDataInput(InputGenerateTransactionPayloadData data) =>
    data is InputScriptData;
